encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:entry>", views.entry_page, name = "entry_page"),
    path("creating", views.entry_page, name = "content"),
    path("<str:entry>/editing", views.editor, name = "editing"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
import random
from . import util
import markdown2

class SearchForm(forms.Form):
    search = forms.CharField(label="", widget=forms.TextInput(attrs={'placeholder': 'Search Encyclopedia'}))

class NewContent(forms.Form):
    title = forms.CharField(label="Title", widget=forms.TextInput(attrs={
        'placeholder': 'Enter the title of the article',
        'class':'form-control',
        'id':'exampleFormControlInput1'
    }))
    content = forms.CharField(label="Content", widget=forms.Textarea(attrs={
        'placeholder': 'Enter the article',
        'class': 'form-control',
        'id': 'exampleFormControlTextarea1',
        'rows':'3'
    }))

class EditContent(forms.Form):
    title = forms.CharField(label="Title", widget=forms.TextInput(attrs={
        'placeholder': 'Enter the title of the article',
        'class':'form-control',
        'id':'exampleFormControlInput1',
        'readonly':'readonly'
    }))
    content = forms.CharField(label="Content", widget=forms.Textarea(attrs={
        'placeholder': 'Enter the article',
        'class': 'form-control',
        'id': 'exampleFormControlTextarea1',
        'rows':'3'
    }))

def index(request):
    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            search = form.cleaned_data["search"]
            if search.lower() in util.lower_casing(util.list_entries()):
                return HttpResponseRedirect(reverse("wiki:entry_page", args=[search]))

            result = util.Filter(util.list_entries(), [search])
            return render(request, "encyclopedia/index.html", {
                "title": "Searched Results",
                "entries": result,
                "method": request.method,
                "form": SearchForm(),
            })
    return render(request, "encyclopedia/index.html", {
        "title": "All Pages",
        "entries": util.list_entries(),
        "form":SearchForm(),
        "random_entry":random.choice(util.list_entries())
    })

def entry_page(request, entry):
    if entry == "creating":
        if request.method == "POST":
            form_content = NewContent(request.POST)
            if form_content.is_valid():
                title = form_content.cleaned_data["title"]
                content = form_content.cleaned_data["content"]
                if title.lower() in util.lower_casing(util.list_entries()):
                    return render(request, "encyclopedia/error_page.html")
                else:
                    util.save_entry(title, content)
                    return HttpResponseRedirect(reverse("wiki:entry_page", args=[title]))
        else:
            return render(request, "encyclopedia/content_creator.html", {
                "form_content": NewContent(),
                "random_entry": random.choice(util.list_entries())
            })
    else:
        return render(request, "encyclopedia/entry_page.html", {
            "entry": entry,
            "content": markdown2.markdown(util.get_entry(entry)),
            "random_entry": random.choice(util.list_entries())
        })

def editor(request, entry):
    arr1 = entry.split("/")
    if request.method == "POST":
        form_edited = EditContent(request.POST)
        if form_edited.is_valid():
            title = form_edited.cleaned_data["title"]
            content = form_edited.cleaned_data["content"]
            util.save_entry(title, content)
            return HttpResponseRedirect(reverse("wiki:entry_page", args=[title]))
    return render(request, "encyclopedia/editor.html", {
        'title':arr1[0],
        "formEdit":EditContent(initial={'title':arr1[0] ,'content': util.get_entry(arr1[0])}),
        "random_entry": random.choice(util.list_entries())
    })

encyclopedia/templates/encyclopedia/content_creator.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Creating New Content
{% endblock %}

{% block body %}
    <form action="{% url 'wiki:content' %}" method="post">
        {% csrf_token %}
        {{ form_content }}
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>


{% endblock %}

encyclopedia/templates/encyclopedia/editor.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Editing Content
{% endblock %}

{% block body %}
    <form action="{% url 'wiki:editing' title %}" method="post">
        {% csrf_token %}
        {{ formEdit }}
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>


{% endblock %}

encyclopedia/templates/encyclopedia/entry_page.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
    {{ entry }}
{% endblock %}

{% block body %}
    {{ content|safe }}
    <form action="{% url 'wiki:editing' entry %}" method="GET">
        <a href="{% url 'wiki:editing' entry %}"><input class="btn btn-primary" type="button" value="Edit"></a>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/error_page.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
    Error
{% endblock %}

{% block body %}
    <div class="page-wrap d-flex flex-row align-items-center">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 text-center">
                <span class="display-1 d-block">Already exists</span>
                <div class="mb-4 lead">Topic with this title already exists.</div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>{{ title }}</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="/{{ entry }}">{{ entry }}</a></li>

        {% empty %}
            <div>No result found</div>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:index' %}" method="post">
                    {% csrf_token %}
                    {{ form }}
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:content' %}">Create New Page</a>
                </div>
                <div>
                    <a href="/{{ random_entry }}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>